SELECT * FROM TABS;
SELECT * FROM PLACES;

--장소 제안 관련 테이블 생성 > PROPOSAL, PROPOSAL_IMG
SELECT * FROM PROPOSAL;
SELECT * FROM PROPOSAL_IMG;
SELECT * FROM CREW;
--장소 제안 대표 이미지 PK 관련 시퀀스 만듦 
CREATE SEQUENCE SEQ_PROPOSEIMG;

SELECT SEQ_PROPOSAL.NEXTVAL FROM DUAL;
SELECT SEQ_PROPOSAL.CURRVAL FROM DUAL;

--INSERT INTO PROPOSAL VALUES(#{memberId},'P'||SEQ_PROPOSAL.NEXTVAL,#{title},#{areaCode},#{sigunguCode},#{address},#{cat2},#{mapx},#{mapy},DEFAULT,DEFAULT,#{info})

SELECT * FROM PROPOSAL P
LEFT JOIN PROPOSAL_IMG I
USING (PROPOSAL_ID)
WHERE PROPOSAL_ID='P3';

SELECT * FROM PROPOSAL;
SELECT * FROM PROPOSAL_IMG;
SELECT * FROM PLACES WHERE CONTENTID = 'PP1';

--제안한 장소를 PLACES테이블에 등록하기 위해 시퀀스를 생성함 : SEQ_CONTENTID
--PROPOSED PLACE라는 의미에서 PP를 붙이기로 함...

SELECT SEQ_CONTENTID.NEXTVAL FROM DUAL;
SELECT 'PP'||SEQ_CONTENTID.NEXTVAL FROM DUAL;

SELECT * FROM PROPOSAL WHERE PROPOSAL_ID='P10';

-- 좋아요 TABLE
SELECT * FROM LIKES;
-- 좋아요 상세 TABLE
SELECT * FROM LIKES_INFO;

--SEQ_LIKES : LIKES테이블의 PK를 위해 SEQUENCE를 만듦

SELECT * FROM LIKES WHERE MEMBER_ID = 'admin08';