SELECT * FROM TABS;
SELECT * FROM PLACES;

--장소 제안 관련 테이블 생성 > PROPOSAL, PROPOSAL_IMG
SELECT * FROM PROPOSAL;
SELECT * FROM PROPOSAL_IMG;
SELECT * FROM CREW;
--장소 제안 대표 이미지 PK 관련 시퀀스 만듦 
CREATE SEQUENCE SEQ_PROPOSEIMG;

SELECT SEQ_PROPOSAL.NEXTVAL FROM DUAL;
SELECT SEQ_PROPOSAL.CURRVAL FROM DUAL;

--INSERT INTO PROPOSAL VALUES(#{memberId},'P'||SEQ_PROPOSAL.NEXTVAL,#{title},#{areaCode},#{sigunguCode},#{address},#{cat2},#{mapx},#{mapy},DEFAULT,DEFAULT,#{info})

SELECT * FROM PROPOSAL P
LEFT JOIN PROPOSAL_IMG I
USING (PROPOSAL_ID)
WHERE PROPOSAL_ID='P3';
